#!/bin/bash
git init -q
git remote add origin https://github.com/Legends-Mkt/docker_testnegative
git fetch origin -q
git checkout origin/master -- compose
mv compose/* ./
mv compose/.gitignore ./
rm -rf compose .git
git init
mkdir ./magento
mkdir ./magento/app/etc
mv env.php ./magento/app/etc
mv config.php ./magento/app/etc
cd ./magento 
git clone -b pre-master-dev3 git@github.com:Legends-Mkt/testnegative_magento.git .
