version: '2.1'
services:
  db:
    hostname: db.claude
    image: 'mariadb:10.4'
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    ports:
      - '33066:3306'
    volumes:
      - './mnt:/mnt:rw,delegated'
      - './db:/var/lib/mysql'
    healthcheck:
      test: 'mysqladmin ping -h localhost -pmagento2'
      interval: 30s
      timeout: 30s
      retries: 3
    command: '--auto_increment_increment=3 --auto_increment_offset=2'
    networks:
      magento:
        aliases:
          - db.claude
  fpm:
    hostname: fpm.claude
    image: 'magento/magento-cloud-docker-php:7.2-fpm-1.2.4'
    volumes:
      - './magento:/app:rw,delegated'
      - './magento/vendor:/app/vendor:rw,delegated'
      - './magento/generated:/app/generated:rw,delegated'
      - './mnt:/mnt:rw,delegated'
      - '~/.composer/cache:/root/.composer/cache:rw,delegated'
    networks:
      magento:
        aliases:
          - fpm.claude
    depends_on:
      db:
        condition: service_healthy
  web:
    hostname: web.claude
    image: 'magento/magento-cloud-docker-nginx:1.19-1.2.0'
    volumes:
      - './magento:/app:ro,delegated'
      - './magento/vendor:/app/vendor:ro,delegated'
      - './magento/generated:/app/generated:ro,delegated'
      - './mnt:/mnt:rw,delegated'
    environment:
      - WITH_XDEBUG=0
    networks:
      magento:
        aliases:
          - web.claude
    depends_on:
      fpm:
        condition: service_started
  varnish:
    hostname: varnish.claude
    image: 'magento/magento-cloud-docker-varnish:6.2-1.2.0'
    networks:
      magento:
        aliases:
          - varnish.claude
    depends_on:
      web:
        condition: service_started
  tls:
    hostname: tls.claude
    image: 'magento/magento-cloud-docker-nginx:1.19-1.2.0'
    volumes:
      - './mnt:/mnt:rw,delegated'
    networks:
      magento:
        aliases:
          - tls.claude
    environment:
      UPSTREAM_HOST: varnish
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      varnish:
        condition: service_started
  elasticsearch:
    hostname: elasticsearch.claude
    image: 'magento/magento-cloud-docker-elasticsearch:7.11-1.2.4'
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      magento:
        aliases:
          - elasticsearch.claude
    depends_on:
      web:
        condition: service_started
  redis:
    hostname: redis.claude
    image: 'magento/magento-cloud-docker-redis:5.0'
    networks:
      magento:
        aliases:
          - redis.claude
    depends_on:
      web:
        condition: service_started
  rabbitmq:
    hostname: rabbitmq.claude
    image: 'rabbitmq:3.8.17'
    networks:
      magento:
        aliases:
          - rabbitmq.claude
    ports:
      - '5672:5672'
      - '25672:25672'
    depends_on:
      web:
        condition: service_started
networks:
  magento:
    driver: bridge
